export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "키워드로 분류된 다양한 글 모음",
  headline: "24시간 잠들지 않는 브런치 책방이 문을 엽니다.",
  description: "지금 등록하시면 10%할인된 가격에 숙박, 여행권 선물로 드립니다.",
  buttonLabel: "등록하기",
  imgStart: false,
  img: require("../../images/svg1.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "project",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "키워드로 분류된 다양한 글 모음",
  headline: "24시간 잠들지 않는 브런치 책방이 문을 엽니다.",
  description: "지금 등록하시면 10%할인된 가격에 숙박, 여행권 선물로 드립니다.",
  buttonLabel: "더 알아보기",
  imgStart: true,
  img: require("../../images/svg2.svg"),
  alt: "forest",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "키워드로 분류된 다양한 글 모음",
  headline: "24시간 잠들지 않는 브런치 책방이 문을 엽니다.",
  description: "지금 등록하시면 10%할인된 가격에 숙박, 여행권 선물로 드립니다.",
  buttonLabel: "시작하기",
  imgStart: false,
  img: require("../../images/svg3.svg"),
  alt: "paper",
  dark: false,
  primary: false,
  darkText: true,
};
